### ISSUE TITLE
login (reglas de registro @estudiante.uam.es @uam.es)

### ISSUE THREAD

**Issue by danielss24** [danielss24/BaseApp_VUE_IRAV#13]

**Comment by cabelotaina** [comment]
Guys I have this working but we have some problem here:

![image](https://user-images.githubusercontent.com/1827173/80284221-80a01e80-871d-11ea-969b-3989e8f20cb3.png)

for example this email don't exists but I can create a new user with this email, and for any email. We can solve this 2FA auth.

Any good idea to improve our authentication system?

Ah this is another example

![image](https://user-images.githubusercontent.com/1827173/80284533-6bc48a80-871f-11ea-89b5-b8a07ebcc47c.png)

Here someone put gmail as a email, but we show the field in red.
